# [Choice] Node.js version (use -bookworm, and -bullseye variants on local arm64/Apple Silicon): 20, 18, 20-bookworm, 18-bookworm, 20-bullseye, 18-bullseye, 20-buster, 18-buster
ARG VARIANT=18-bookworm
FROM node:${VARIANT}
COPY setup.sh /tmp/setup.sh
RUN /tmp/setup.sh
